name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.6.1"]
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install project dependencies
        run: |
          # repeat to work around https://github.com/python-poetry/poetry/issues/7611
          poetry install || poetry install || poetry install
      - name: Run tests
        run: |
          poetry run pytest .
      - name: Check format
        run: |
          poetry run black --check .
      - name: Run linter
        run: |
          poetry run flake8 .
      - name: Check type hints
        run: |
          poetry run mypy .
      - name: Check imports being sorted
        run: |
          poetry run isort . --check
